openapi: 3.1.0
info:
  title: padmst
  version: '1.0'
  description: ''
servers:
  - url: 'http://localhost:3000/padmst'
paths:
# -----------------------------------
  /monster/list:
    get:
      summary: 查询Monster
      description: Returns a list of resources filtered by attributes and type, sorted by specified criteria
      parameters:
        - name: mainAttr
          in: query
          description: 主属性
          schema:
            type: string
            enum: [name, date, category]
          required: false
          example: name

        - name: subAttr
          in: query
          description: 副属性
          schema:
            type: string
            enum: [public, private, shared]
          required: false
          example: public

        - name: sortBy
          in: query
          description: |
            排序项目:
            - 1 = ID
            - 2 = 卖MP
            - 3 = HP
            - 4 = ATK
            - 5 = RCV
            - 6 = SkillTurn
            - 7 = 稀有度
          required: false
          schema:
            type: integer
            enum: [1, 2, 3, 4, 5, 6, 7]

        - name: sortKbn
          in: query
          description: |
            排序方式:
            - 1 = 升序
            - 2 = 降序
          required: false
          schema:
            type: integer
            enum: [1, 2]
            default: 1

      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                - id: 1
                  name: "Item 1"
                  type: "public"
                - id: 2
                  name: "Item 2"
                  type: "private"

        '400':
          description: Invalid parameters
          content:
            application/json:
              example:
                error: "Invalid parameter value"
                message: "Supported sort values are [asc, desc]"
# -----------------------------
  /team/list:
    post:
      summary: List Team
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
            application/xml:
              schema:
                type: object
                properties:
                  '':
                    type: string
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples: {}
        description: no params
      description: Create a new user.
    parameters: []
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: ID
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    Team:
      title: Team
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        member1p:
          type: array
          items:
            $ref: '#/components/schemas/Monster'
        assist1p:
          type: array
          items:
            $ref: '#/components/schemas/Monster'
    Monster:
      title: Monster
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        attr:
          type: string
          description: メイン属性
        subAttr:
          type: string
          description: サブ属性
